name: Build & Push

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: ${{ inputs.platforms }}
          tags: ${{ inputs.tags }}
